// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBAQZahRDTJhKJHF8U4-YfArIbDShwwnE',
    appId: '1:268465556907:web:456049a906ca0a6db316ee',
    messagingSenderId: '268465556907',
    projectId: 'hitian-inside-69e00',
    authDomain: 'hitian-inside-69e00.firebaseapp.com',
    storageBucket: 'hitian-inside-69e00.firebasestorage.app',
    measurementId: 'G-ZQ6EP2H8N6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARY7ERyXBgQ2XiPiz1HWtd6FNvxSBCMis',
    appId: '1:268465556907:android:2f38dd08ea58c3e5b316ee',
    messagingSenderId: '268465556907',
    projectId: 'hitian-inside-69e00',
    storageBucket: 'hitian-inside-69e00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmJ0CrvkqjHjE4iJuvlFMwGpmxQXXn6Q0',
    appId: '1:268465556907:ios:e27df13a57e6a931b316ee',
    messagingSenderId: '268465556907',
    projectId: 'hitian-inside-69e00',
    storageBucket: 'hitian-inside-69e00.firebasestorage.app',
    iosBundleId: 'com.example.hitianInside',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmJ0CrvkqjHjE4iJuvlFMwGpmxQXXn6Q0',
    appId: '1:268465556907:ios:e27df13a57e6a931b316ee',
    messagingSenderId: '268465556907',
    projectId: 'hitian-inside-69e00',
    storageBucket: 'hitian-inside-69e00.firebasestorage.app',
    iosBundleId: 'com.example.hitianInside',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBAQZahRDTJhKJHF8U4-YfArIbDShwwnE',
    appId: '1:268465556907:web:de4837b27972825eb316ee',
    messagingSenderId: '268465556907',
    projectId: 'hitian-inside-69e00',
    authDomain: 'hitian-inside-69e00.firebaseapp.com',
    storageBucket: 'hitian-inside-69e00.firebasestorage.app',
    measurementId: 'G-4S2MVM2ZD9',
  );
}
